# SQLite for test and production
default_sqlite: &default_sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

test:
  <<: *default_sqlite
  database: storage/test.sqlite3

production:
  <<: *default_sqlite
  database: storage/production.sqlite3
